baseURL = "https://merimerimeri.com/"
languageCode = "en-us"
title = "merimerimeri.com"
enableRobotsTXT = true
sectionPagesMenu = "main"
paginate = 10

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  title = "merimerimeri.com - A blog by Stephen Meriwether"
  description = "A blog by Stephen Meriwether. Stephen writes about technology, the internet, and his life."

[author]
  name = "Stephen Meriwether"

[menu]
[[menu.main]]
  identifier = 'essays'
  name = 'essays'
  title = 'Essays'
  url = '/essays/'
  weight = 1
  
[[menu.main]]
  identifier = 'about'
  name = 'about'
  title = 'About'
  url = '/about/'
  weight = 2
  
[[menu.main]]
  identifier = 'contact'
  name = 'contact'
  title = 'Contact'
  url = '/contact/'
  weight = 3
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_', 'NODE_ENV']

  [security.http]
    methods = ['(?i)GET']
    urls = ['.*']

