baseURL = "https://merimerimeri.com/"
languageCode = "en-us"
title = "merimerimeri.com"
enableRobotsTXT = true
sectionPagesMenu = "main"
paginate = 10

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  title = "merimerimeri.com - Stephen Meriwether's website"
  description = "I'm Stephen and this is my website about technology and my life."

[author]
  name = "Stephen Meriwether"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_', 'NODE_ENV']

  [security.http]
    methods = ['(?i)GET']
    urls = ['.*']

